apiVersion: v1
kind: Service
metadata:
  name: quote-api-service
spec:
  # Use NodePort to easily access the service from outside the cluster for local testing
  type: NodePort
  selector:
    app: quote-api # This must match the labels in the deployment
  ports:
    - protocol: TCP
      port: 80       # Port on the service
      targetPort: 8080 # Port on the pods